name: CI
on:
  [ workflow_dispatch, workflow_call ]

jobs:
  build:
    runs-on: 
      group: group_a
    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
